### ISSUE TITLE
Downloaded, installed and tried to run...

### ISSUE THREAD

**Issue by RiccardoBiemmi** [RolandCsibrei/babylonjs-vue3-javascript#1]
... without touching a line of code and I get two errors right out of the gates. I have Node 18.18.0 installed.

ERRORS
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
-  Building for production...D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\loader-runner\lib\LoaderRunner.js:114
                        throw e;
                        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\cache-loader\dist\index.js:147:7
    at D:\Downloads\babylonjs-vue3-javascript-basic-setup-main\node_modules\graceful-fs\graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:200:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by RolandCsibrei** [comment]
Hi!

https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
